/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package TOTEC;

import CyanTestingTools.AAT;
import TOTEC.TOTEC;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;

/**
 *
 * @author vitorcasadei
 */
public class SelectMainDirectory extends javax.swing.JFrame {
    private String file;
    private boolean isOK = true;
    /**
     * Creates new form SelectMainDirectory
     */
    public SelectMainDirectory() {
        initComponents();
        groupButton();
        this.SelectDirectorybt.setEnabled(false);
        this.Directorytf.setEnabled(false);
        setLocationRelativeTo(null);
        setVisible(true);
        super.getRootPane().setDefaultButton(this.TOTECbt);
        this.TOTECbt.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void groupButton() {

        ButtonGroup bg1 = new ButtonGroup( );

        bg1.add(Yescb);
        bg1.add(Nocb);

    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Group = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Yescb = new javax.swing.JRadioButton();
        Nocb = new javax.swing.JRadioButton();
        Directorytf = new javax.swing.JTextField();
        SelectDirectorybt = new javax.swing.JButton();
        TOTECbt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TOTEC (Tools for Teste Cases) - Cyan Language Testing Tools");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setText("Do you want to Select your Main Directory?");

        Yescb.setForeground(new java.awt.Color(1, 1, 1));
        Yescb.setText("Yes");
        Yescb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YescbActionPerformed(evt);
            }
        });

        Nocb.setForeground(new java.awt.Color(5, 5, 5));
        Nocb.setSelected(true);
        Nocb.setText("No, use Default");
        Nocb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NocbItemStateChanged(evt);
            }
        });
        Nocb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NocbActionPerformed(evt);
            }
        });

        SelectDirectorybt.setText("...");
        SelectDirectorybt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelectDirectorybtMouseClicked(evt);
            }
        });

        TOTECbt.setText("Execute TOTEC");
        TOTECbt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TOTECbt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TOTECbtMouseClicked(evt);
            }
        });
        TOTECbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOTECbtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(Yescb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Nocb)
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(Directorytf)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(SelectDirectorybt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(TOTECbt)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Yescb)
                    .addComponent(Nocb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Directorytf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectDirectorybt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TOTECbt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void YescbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YescbActionPerformed
        // TODO add your handling code here:
        if(this.Yescb.isEnabled()){
            this.SelectDirectorybt.setEnabled(true);
            this.Directorytf.setEnabled(true);
        } else {
            this.SelectDirectorybt.setEnabled(false);
        }
        
    }//GEN-LAST:event_YescbActionPerformed

    private void NocbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NocbItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_NocbItemStateChanged

    private void NocbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NocbActionPerformed
        // TODO add your handling code here:
        if(this.Nocb.isEnabled()){
            this.SelectDirectorybt.setEnabled(false);
            this.Directorytf.setEnabled(false);
        } else {
            this.SelectDirectorybt.setEnabled(true);
        }
    }//GEN-LAST:event_NocbActionPerformed

    private void SelectDirectorybtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectDirectorybtMouseClicked
        // TODO add your handling code here:
        file = AAT.selectDirectory();
        this.Directorytf.setText(file);
    }//GEN-LAST:event_SelectDirectorybtMouseClicked

    private void TOTECbtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TOTECbtMouseClicked
        // TODO add your handling code here:
        
        if(this.Yescb.isSelected()){
            if(this.Directorytf.getText().equals("")){
                isOK = false;
                this.Directorytf.setBorder(BorderFactory.createLineBorder(Color.red));
            } else {
                isOK = true;
                TOTEC.main(new String[]{this.Directorytf.getText()});
            }
        } else {
                TOTEC.main(new String[]{});
        }
        this.dispose();
    }//GEN-LAST:event_TOTECbtMouseClicked

    private void TOTECbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOTECbtActionPerformed
        // TODO add your handling code here:
        if(this.Yescb.isSelected()){
            if(this.Directorytf.getText().equals("")){
                isOK = false;
                this.Directorytf.setBorder(BorderFactory.createLineBorder(Color.red));
            } else {
                isOK = true;
                TOTEC.main(new String[]{this.Directorytf.getText()});
            }
        } else {
                TOTEC.main(new String[]{});
        }
        this.dispose();
    }//GEN-LAST:event_TOTECbtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectMainDirectory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectMainDirectory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectMainDirectory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectMainDirectory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectMainDirectory().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Directorytf;
    private javax.swing.ButtonGroup Group;
    private javax.swing.JRadioButton Nocb;
    private javax.swing.JButton SelectDirectorybt;
    private javax.swing.JButton TOTECbt;
    private javax.swing.JRadioButton Yescb;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
